export enum PARKING_SPOT {
  COMPACT = "COMPACT",
  LARGE = "LARGE",
  HANDICAPPED = "HANDICAPPED",
  MOTORCYCLE = "MOTORCYCLE",
}

export enum PARKING_STATUS {
  AVAILABLE = "AVAILABLE",
  OCCUPIED = "OCCUPIED",
  NOT_IN_USE = "NOT_IN_USE",
}
